### ISSUE TITLE
Blank page after run shadowd_connector.php

### ISSUE THREAD

**Issue by Mato-Z** [zecure/shadowd_php#1]
Hello,

I have installed shadowd according this procedure https://shadowd.zecure.org/overview/php_connector/, I want connect it with Drupal 7 installation. I create virtualhost and added php_value  auto_prepend_file  "/usr/share/shadowd/shadowd_connector.php". In the shadowd_connector.php I have changed define('SHADOWD_CONNECTOR_CONFIG', '/etc/shadowd/connectors.ini'); to /etc/shadowd/shadowd.ini. After the Apache restart I see only blank page... After comment php_value  auto_prepend_file  "/usr/share/shadowd/shadowd_connector.php" line all is ok again. Where is the problem please? Of course I have completed all tasks in procedure in "Getting started".
Thanks.

**Comment by zit-hb** [comment]
Hi Mato,

First, I recommend to enable _debug_ in the configuration file. This way you can look at the error log of your web server (probably /var/log/apache2/error.log) to see what causes this. I limit such output to the error log for security reasons (to avoid information disclosure).

Some possibilities are:
- You forgot to add (and/or uncomment) the _id_ and _key_ in the config. Both are required.
- The php or ini file are not readable by the web server user.

May I ask why you changed connectors.ini to shadowd.ini? Are you trying to combine both [connectors.ini](https://github.com/zecure/shadowd_php/blob/master/misc/examples/connectors.ini) and [shadowd.ini](https://github.com/zecure/shadowd/blob/master/misc/examples/shadowd.ini) to one file?

Best regards,
Hendrik

**Comment by Mato-Z** [comment]
Hi zit-hb, thank you very much, I messed shadow.ini and connector.ini files :-/. Now I entered right parameters in connectors.ini file and it runs... (without blank page) I will use web application as hight interaction honeypot. So I changed observe value to 1. Now is any simply fast way as I can try that it works correctly? How can I generate some test request (I am trying it in virtual environment), which certainly will be displayed in shadowd web interface?
Thanks.

**Comment by zit-hb** [comment]
Ok, very good. You can do something like this to simulate a SQL injection:

```
http://yoursite/index.php?input='/**/UNION/**/SELECT/**/CONCAT(email,':',password)/**/FROM/**/users/*
```

This generates a blacklist impact of 22 with the current filters/detection patterns. Let me know if it worked or not.

It is nice to hear that you plan to use it as a high-interaction honeypot. I use it for this task myself on multiple servers. If your site is a pure honeypot and you do not expect unmalicious requests I recommend to set the global blacklist threshold to a really low value, e.g., 5. Another important thing for a high-interaction honeypot is to set observe to 1, but you have already done that. A lot of attacks start with a probe request before the actual payload is send. It is not unlikely that shadowd detects the probes, so without _observe_ enabled the probes would fail and the attacks would stop before they really started.

And it is important to remember that the honeypot should be good shielded from important stuff, because if the attacker can evaluate PHP code he can also execute system commands. With _observe_ enabled shadowd will not prevent attacks in any way. _disable_functions_ (system,passthru,popen,exec etc.) is a good basic protection, but no guarantee. Rumor has it that PHP had some bugs in the past.

Once you have captured attacks with the blacklist for some time you could consider to also enable the whitelist. It is a bit more work to set it up, but totally worth it. I have created two tutorials that explain how to use it. If you have problems you can also just open an issue and I will try to help.

**Comment by Mato-Z** [comment]
zit-hb really thanks for help! It works! I hope that it will work correctly in "live" operation. Thanks for your advices too. My webhoneypot will be a part of larger hight interaction honeypot which will be provide some services (SSH, web etc...) and it will be completely behind honeywall...

**Comment by zit-hb** [comment]
Sure, you are welcome. Sounds like a nice set-up, good luck with finding some interesting stuff.

**Comment by zit-hb** [comment]
Oh, I totally forgot: It is also very important that you disable the flooding protection of shadowd for a honeypot. Just set the flooding threshold in the profile to _-1_.

**Comment by Mato-Z** [comment]
zit-hb, thanks again for additional information...
