### ISSUE TITLE
encountring error in php connector

### ISSUE THREAD

**Issue by masoudqashqai** [zecure/shadowd_php#16]
i am following the installation from documentation in shadowd.zecure.org , in php connector section i downloaded the folder shadowd_php and copy the src files in  /usr/share/shadowd/php and set
 auto_prepend_file = "/usr/share/shadowd/php/Connector.php"
in my php.ini file , but when i restart apache2 i see this in apache logs

[Sat Sep 07 06:06:38.042510 2019] [:error] [pid 1266] [client 127.0.0.1:41126] PHP Fatal error:  Uncaught Error: Call to undefined function shadowd\\mb_check_encoding() in /usr/share/shadowd/php/Input.php:141\nStack trace:\n#0 /usr/share/shadowd/php/Input.php(137): shadowd\\Input->flatten('localhost', 'HTTP_HOST', 'SERVER')\n#1 /usr/share/shadowd/php/Input.php(137): shadowd\\Input->flatten(Array, 'SERVER', false)\n#2 /usr/share/shadowd/php/Input.php(104): shadowd\\Input->flatten(Array)\n#3 /usr/share/shadowd/php/Connection.php(75): shadowd\\Input->getInput()\n#4 /usr/share/shadowd/php/Connector.php(51): shadowd\\Connection->send(Object(shadowd\\Input))\n#5 /usr/share/shadowd/php/Connector.php(98): shadowd\\Connector::start()\n#6 {main}\n  thrown in /usr/share/shadowd/php/Input.php on line 141

i am using php 7.0 and ubuntu 16.04

**Comment by zit-hb** [comment]
The likely cause is that the package `php-mbstring` is not installed. Try to run `apt install php-mbstring` and restart Apache.

**Comment by masoudqashqai** [comment]
that did the trick, thanks

**Comment by Christian1998** [comment]
Maybe adding a check to check if the function is available? :)

**Comment by zit-hb** [comment]
Yea, I should do that and I will. I still have some features that I want to implement for this connector, like custom error pages.

I wish I could just use Composer and the requirement checks of it but to be honest it is not a good idea to install the connector with "composer require" because then it is only loaded when the autoloader is loaded. So in case an attacker drops a custom PHP file on the server that would not be the case.

Anyway, I will create a ticket and add it when I find the time. If someone is interested in doing this, I also welcome pull requests!
