### ISSUE TITLE
Exception thrown when configure the report feature

### ISSUE THREAD

**Issue by dattmckdj** [zecure/shadowd_php#50]
Hi,

I receive this exception when attempting to use the report feature.
![image](https://user-images.githubusercontent.com/66473757/149769191-a9bcdc80-0ea9-4e63-9737-60e740ba162d.png)
I am hoping the issue can be fixed and the report can be sent.

Best regards,
DatTM

**Comment by zit-hb** [comment]
Hello DatTM and thanks for the report! Just for clarification, this issue is not in this project but in `zecure/shadowd_ui`.

I have released a new version for shadowd_ui that resolves the issue. To use it first you have to specify your mail settings in the `docker-compose.yml` of shadowdctl. It could look like this:

```
  web:
    environment:
      - "SHADOWD_MAILER_TRANSPORT=smtp"
      - "SHADOWD_MAILER_HOST=smtp.gmail.com"
      - "SHADOWD_MAILER_PORT=465"
      - "SHADOWD_MAILER_ENCRYPTION=ssl"
      - "SHADOWD_MAILER_AUTH_MODE=plain"
      - "SHADOWD_MAILER_USER=foo.bar"
      - "SHADOWD_MAILER_PASSWORD=xxx"
```

Then you have to update and restart Shadow Daemon and you are good to go:

```
./shadowdctl down
./shadowdctl pull
./shadowdctl up -d
```

**Comment by dattmckdj** [comment]
Hi zit-hb,

Thank you for the response. 
I have followed your instruction above and rerun the report command successfully. 
However, I have not received any email from the account configured in the .yml file (my personal Gmail account) after recreating multiple SQL injection simulations.
Is the report only sent after the configured time or each time an attack occurs?

Best regards,
DatTM

**Comment by zit-hb** [comment]
Hi DatTM,

That is good to hear!

The command only sends an e-mail when it is executed. The idea is that you use a cronjob or something like that to run it whenever you like.
